tls:
  certificates:
    - certFile: /certs/homelab.pem
      keyFile: /certs/homelab-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/homelab.pem
        keyFile: /certs/homelab-key.pem